# Before using autogenerated filters - update the knowledge base execution IAM role with right permissions
import boto3
import config
import json
import time
class permissionUpdate:
    def __init__(self, kb_id):
        self.iam = boto3.resource('iam')
        self.client = boto3.client('iam')
        self.kb_id = kb_id
        self.bedrock_agent_client = config.bedrock_agent_client
        self.attached_policies = None
        self.role_name = None
        self.get_attached_policies()

    def get_attached_policies(self):
        get_kb_response = self.bedrock_agent_client.get_knowledge_base(knowledgeBaseId = self.kb_id)
        role_arn = get_kb_response['knowledgeBase']['roleArn']
        self.role_name = role_arn.split('/')[-1]
        response = self.client.list_attached_role_policies(RoleName=self.role_name)
        self.attached_policies = response['AttachedPolicies']
        self.update_kb_execution_role()

    def update_kb_execution_role(self, region_name=config.region_name):

        for policy in self.attached_policies:
    
            print(policy['PolicyArn'])
            policy_name = policy['PolicyName']
            policy_arn = policy['PolicyArn']
    
            if 'FoundationModel' in policy_arn:
                print('Updating FoundationModel policy: ',policy_arn)
                policy = self.iam.Policy(policy_arn)
                version = policy.default_version
                policyJson = version.document
                policyJson['Statement'][0]['Resource'].append('arn:aws:bedrock:{}::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0'.format(region_name))
                policyJson['Statement'][0]['Resource'].append('arn:aws:bedrock:{}::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'.format(region_name))
                policyJson['Statement'][0]['Resource'].append(f'arn:aws:bedrock:{region_name}::foundation-model/{config.TEXT_GENERATION_MODEL_ID}')
                policyJson['Statement'][0]['Resource'].append(f'arn:aws:bedrock:{region_name}::foundation-model/{config.EVALUATION_MODEL_ID}')  
                policyJson['Statement'][0]['Resource'].append(f'arn:aws:bedrock:{region_name}::foundation-model/{config.AMAZON_RERANKER_MODEL_ID}') 
                policyJson['Statement'][0]['Resource'].append(f'arn:aws:bedrock:{region_name}::foundation-model/{config.COHERE_RERANKER_MODEL_ID}') 

                self.client.detach_role_policy(RoleName=self.role_name,
                    PolicyArn=policy_arn)
                response = self.client.delete_policy(
                    PolicyArn=policy_arn
                )
                print(response)
                response = self.client.create_policy(
                    PolicyName= policy_name,
                    PolicyDocument=json.dumps(policyJson)
                )
                print(response)
            
                self.client.attach_role_policy(
                    RoleName=self.role_name,
                    PolicyArn=policy_arn
                )
        time.sleep(30)